server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: "aimbot1129"
    sources:
      youtube: true
      soundcloud: true
      twitch: true
      vimeo: true
      bandcamp: true
      http: true
      local: false
    youtubeSearchEnabled: true
    spotify:
      clientId: "aa5706fb4367451aa52c63bb95f9e4d6"
      clientSecret: "c056dcb5cfc14f1aa7682cd393f9833b"
      countryCode: "US"
